### ISSUE TITLE
Why the JS file?

### ISSUE THREAD

**Issue by hmil** [krzkaczor/TypeStrict#3]
Hi, I was wondering why you are defining your main file as js instead of json? I believe you only use js to extend `tslint-microsoft-contrib` and `tslint-sonarts`. Then why not just "extend" those libs the same way a user would extend yours, from json?

**Comment by krzkaczor** [comment]
I don't want to fully extend these other rulesets since I just want hand pick couple of rules. Otherwise I would need to explicitly switch off some rules which will be hard to maintain.

I didn't find a way to do this without specifying `rulesDirectory` and thus I needed to get the first path.

Is using `.js` file causing any problems for you?

**Comment by hmil** [comment]
Oh ok it makes sense.
It is not causing any problem, I was just surprised to find a JS file in this project and curious to know the reason why. If anything, you could abuse the node resolution algorithm and specify this for instance to stick to json: `"rulesDirectory": [ "tslint-sonarts/lib/rules/useTypeAliasRule" , "tslint-microsoft-contrib"]`... But I'm not sure it'd be worth the trouble.
